print([[

//----------------------------------------\\
--------------------------------------------
			  Energy Rush V2
--------------------------------------------
		  Created by GT4XSTRATUS
--------------------------------------------
Anyone who is claiming to have made this is
probably lying, if you aren't sure, my
username is Stratus_bl.
--------------------------------------------
\\----------------------------------------//

]])

print([[

                                                                                                            .          
 ======-=====----=+=:==++--==+-===++===+=======----:::::.:............:..:::::-:--:-=---...:++=-:-=====----..@@+ .---: 
 ====-=---==+=-:--==*+===+++==-==-==============--.:-.... .............:.::-::-:---:.....=+=-:::::...::::::..+@@# .::. 
 =+=======---:-=-::..:========-========--====----:=+++-: +.............:.:::::--.:-:..::---:::.:..::::::::--. @%@* ..: 
 --====--::::::-===-=-:----===========-------:.:.....:.:+.  ...... .    .::.:-:--:....:--:::-:--=----::::---:. @*** .: 
 -:--===..:====----======-============-------:*@@#.@*@@:#@:        .=#@.   :-=-:::::-=--=------------------:::. @@@  - 
 -:%.==: @ ---=----::::---==----=--====+====:  -%*@@@@%:@@@     .=%@#@#@@@#.:.:..::-::.:-:--::::::::-:-:::::-::..@@@   
 . @... @@:=----====---:-::::::-----::-:---: .@+#=:.@@@+@=++@@@+@#+*+=.  @@ -::.::-==-----:::------:::::::-:---. @@@@  
 @.@@- @@ :=-===--====+-===--=:::..:::::::.  @@@ @@@# ..+%=*=-@%.==@@@@ @@ .--===-------------::-----------:::::. @@@@ 
:@  @ -@%   ...:-======-=-------====-::--=.@@@#-@@. .:@% @%@@@@@@@*+=@@@@ .--:==--::--------===-----:-----==----:. @@@ 
-%@@@@@@@+@@@@@@--=----=-----:::::--:-=::: @@@@@@  =@@@@#@@@@@+#%=###+=@@ .:::-:::--:.--------::-===---:::::---:::. @@ 
  @ ##@@ @ -@   :-==++=--========--====-==.   %@. -  .  .   .:+#%@%@@@%%@@ =-.:-==-=-:=---------::::::-==----:====-..@.
-@@ @@*@@ @@  @.==--++=++===-==-====--=-=-.   @@:#@@@@@@@@@@@@@@%@@@@+*-@@..%@-:-=-====---------::--:::---===-------.**
% @@*+*@@ @- @@ :-::-+=+****====----------.@@@@* @:@*@%@@+#***%+---:+@%*%@:-=+*%:-=-=-====----::---===+-=-----------. *
@ @@ @@*@@@@@ @..- ....::..:::-==-==+++=== @@.@=@@.@#@-@   @@   @#+-@#@*=@..*+*%:-=----::-----==*+*++-=++====--=====-. 
@@@=##@@.*@%@@=@ *#@@= ..:.--=-=====...=== @@=@=*@*%**.=#@@=.@@=----@%@*@@ :++=.:--=-========-+=====++====-====--:.:-= 
+@@  @#=+*@@%%@@@%@- :%#%. :.::--=-: @  := @@.@%@@%@@@@@@@:@@**@%%%@@=%*@@ =:#=-++-==+++++++++====-==--=-=::-::.:=+==+ 
=%@@@.@@.@@@@*#@@%@@@%@%%@#%#.   .  :@@+   @@@@@@ #@@%@#@=.   @@@@@@@@*@@..-.#-:  .==-=++++=====++==-::---:.::--::-:-. 
:#%@@@@@@@%@@#@%@@%@%%@#@@@==:-@@@@@=:%@@@ @=  @#*@@%%@*@@@@@@@@=@@%@@@@#@ ...  %@+.=------=-==--:++===+=-:=:.....:::- 
 @%@@@@%%%@@@#:@ @%#@#@%%==@@@@ *-#@@@%%@@@@@@@%@%*@@@@@@@@@@%%#@@@% ===@@@ -@@@@@@   .    .--:-==-======+++=+--:-:..: 
*@@#=#@@@@@ @@@@.@@@@@=.@@@ @@@@@@#@ =#@#@%@*#%@@#@#%@@@+%#-%=+@%@@@=@@@%%@@@@@@@@@@@@  @@@.=====+====-===:..:--==++++ 
:@=*@%%@ @@@@@% @@ @.-@@@.@: -*%%@@@@@@%%%@=@@#@%#@##@@@@@@#@@@@@@%+@%@%@%%@@@@%%%@@@@@@@@ .======++*++===-==--==+==== 
+%=@%@%@@@%@@@:.@@.=@@@++=@@@@##%@%%##%@@@%*@@%@%@*@@.*#+#@@#@..=@@%@@@%@%%*-@@@@+*+:*@%@@@.---==::::::==+++=======+=+ 
%*+%%@*@%@%@@@@@= @@%**%@*++@@@@#*#@@@%%@@@@@@#@@@%@@=%@@+##-@=%+@@#@%%%@%%@%@.:.%@@@%@@@@@ =-=--========:..:-=====+=- 
=%@@#@@%=###@@@:#@@%%#%@%@@@@=@@@@%#%#%%@@+*#=##%###@*@.*=.:@#:@ @@#@%@@@@@@@@@@@@@@@##@@@@.##+*=--=====+=@@@ ..:... - 
-*%#%=:@@-@=#@@.@@+@@%%%@@@  *@@%@@@@*+=@*@@%@@@@%@#+*@#@@@@@@@@@@@#@@@@@@%%@@*@@@%###@@@# .:--:-==+=-:...  @@@= .@@@@.
-*#@@@@@@@@@*@ @@%##@#@@@  %@@@@@@@%@@@%@%%%%%%@%#=@@*%*@:%-+*%*##@%%@@@@@#@@@#@##%@@@@%. .--==+:.:.:@*%@+@=:-*@@@ +@@ 
+@@#-%##%=+**@ @@@@@@@@# #@@@@@@@@@@@@@%@@@@@@%%#@*@##%#@+@@@-+%%@@@%*= .@%  -@@@@@@@#%@@@-.%%.-*@+@@.+@+# :@   #@@@.: 
+@@@#@#*#%@%@@ @@%@   -%@@%#++@@@@@*@@@@@@%@@@@@@%@@@@+@@*@#%=@@@@%#+**%##@@@#@%@%%@@%#%@@@@  --%... @ +.-%*@@@ %   :@.
+@@#:%#@@@#:=%-#@# @@@.-+*@@@@#=@@@@@@@@ @@@ @@@%%#%%*@%%@%%*@. @@%%%@@@@@@% @@@-@@@@@@@**%@@@@@=@@@+@*@@+.=#.%*.@@@ @ 
:#*%%**@*%+@@#@ @@@@  @@@*=%@+@@%.-.+==@ @=@ @@@@@@@@%@@@@##@=@@ @@@@@@.-+:@@ .#%@*@@@*@@@@%*@%#%@*@ .   @@@ @%@@ @*@ -
+@@@@@@#@%%%%@@=: @  @@@@@#*@+@@@%    :@*@@@  .%.-@@@@#:#%%#@=@@@@. @ - %  **@@+.@-=#@@@++=@@@@@@@@@@@+@@=.@ ##+@:+.--:
+%@@#@@@@@%@@-@@.@ @@@@@@@@+@=@%@@-+.: @@@@@@@@@@%%#@#%*@@@@%#@    .@#@@@@@= @ @@@@@#@#@@@@@@@@%*#@@@@@=+# @=+@@@#=.@%.
:*%@#%*@@*#*@@@@+@ .. ::-*%#@@@%*@@@@@@@@-@@@  .#@@%+*@%@@@%@+@@ .@@@@*% @*+@.@@=:+**##@@@# .  @@%@**@@@.@:%@@@@.##@= %
+@***##+**@*@%@:  @@@@@@@@*=*#@@*@@@@@%@@@. @@@@@@%%@@@@%+*@@%# @@@-.@@@.. +@@*@+%@%-@+@ .=.%%@@@#**##@-=%*%:-@. +::=:@
*@@@@@@@@@@%@%@@@% * -:-=%@@@+=@%@##+#%@@ .@ @#*##@#+::==#=.**@@@@@@@+%@@@@=:=+*+==-%@=*@@-*@..=@@%#*=-* %*+.=%@%@@%* @
+%%@@%##*##*@@-   .@#@%@%##=%@@#%%#%@@@@ . .@@@@@%@@%@@%@@@@@@+@%:@@@.@@@-@@*#-%%%@%*@@@=+-=% @@*@#%@@@@@*:#*%@@@=-:=.@
+#%#%%@@@@@@@@ @@@@@##@@@@@@%-@@%@@%@@@ @ =@@@@@@@@@#=%@@@@@@@@@@*@@@@:+@%%%@@*#*-%@*:#@-@=##%-  @@%#@@@%* ::.@@ - %%@.
-@@@@+#*@**%*#=@@*@@@@@@@.%%@#+=@%%%@.:  @@-+@+@@@@*%@@@*@%@@:#@*%@#@@@:@@@#%@@@%@@+-:@@-.-=.=@%  @@@-+@@@@@+ %#@*-@ @ 
*%@@@@@#@@@@@#@@@@@@@@@@+##@@@*@@%#@@..@  .-=-=*@@#%@@%@%#@%@+@%%@@#@@@@*=@@%#*@@@+ :% :-@@@ .@+ @@:@@@@#=@ :@@@ @%@ @ 
=*#%%#*@@#..@@@@@@@@%@@@%@@@%@@@@@@%@@@:@@@@@@+-@%@@@@%@%@%@%#@+@@@%*=%@#@+#%@@**#@@:.+@:##@%-.@=  .==:@@@%   @@.%@@@*.
*@@@@@@%%@.@@@@@@@@%@@%@@@@@@@@%@@@@%%@#.*#@@%+@%%:@@*@@@@@#+@@@@@###**:@@@=+*%@@%@@@@ **=%@@@  @@@@@:@+@@@@@:.@*+. @+.
*%+**#@#%@@= %@@@@@@@@@@@#@@@@%%@@*#%@@@@@@@#-@@%@=%@@@@@@@@@@@@@@@+%@@%@%@@@##**@#@@@@# -@@%-@@@@@@@@+@%#.:.. @:@:+##-
-@@@@@%@@@@ -@+#@@#@#%@%%@@@@@@@@#-@@@  #=*==+@@@@.#@@@@@+*#@@%%%%#%@#%@@@##@@%%%##*=@@@@@@@@%@@%%%#@@@@#@-@+@ @+#.@ @:
#=@@%@%%#@*@@@  @##@@@#%#@@###%-*%@@%@@@@@@@@+@.=@#@%#*@@@=*@@@@@@@%#@@+#@@@+@@@*#@@%##@%@@@#@@@## @@@@@@- @ @ @. @% @ 
*@@%@%%@%@@ %@ @@@@@%%%%%@#%#%@%@@#@@@@@@@@@@@@@@=@:#%##@@:@%@%@##@%=@@%#*+*%#@@@#%%%@%#@@@@#@-.%@.  @@%@@*#-+=@ +@+ @.
-@%#%*#%@@--@:@@###@=*@@@#@@%%#@%%%@@@%%%%%@@@@@@@*@@@@%%@@@@@#%%@@@@-+@@@@%@##@@@%#@@@@#@@@@@#-@@@%..%##@@%  .@ # . @.
#@@@@@%#@* %% @%%@@@#%%%#%#%@@#@@@@@@@@@@@@@@@@@@#@@+*%@@%%@@@@*@%@@@:.@@%%@@+#%-@@*:#@###+@@@@@%%@@@@@@@@@%@-#@@@.@+@.
*@@@@%@@@ @@.@@%@@@@@%%@#%%%@@@##*@.@@@**##%#@@@@%#=#@%%**@@##@%%@@@@-:@@@=.+*%%++@@* *+%%@%*@@@@@-.@=%@***@@@@:@@@.@::
#@@%%#@@ .-@  @%@@@@@@@@@@@@@ #@@@@.:.@@@@@@@@@@@#@@@@=*@@@@@@@@@@@@@%*==%@@+#@*%%:@@@ =#*#@%#@@@@ *%.# @@@@@.@@@@@  @.
*@@@@%@@ #%.*@@@@@@@@@@%+%*#@@@%=-@ @@@@@@#@@@@@*%@@@%##@%@@@%@+++*#@@@@@@@:%=%#=#@:@@@:.@%%@%%#@#:%@++*+ @@@ -@%. @@@@
*@@@@@@ .#@%@@@@@@@@@*#%#@%%%@@@@@@*=---.@@@@@@#@#@@#@#%#%@@@@@@@@@@@@@@@%@ *#@#**=...@@*.*%@%#*@ -*@*@*%:@@*@@%@-%+@# 
*@@@@@% +@.%@@@@@@@@@@@@@@@@@@% .@@@@@@@@@@@@@%#@@@%=*+#@@@@@@@%@@@@%%@@@%@@ :.== @*@@@%@@.#@@@@@:*-- +:- . #@. @#%..@*
#@@@%@ -*@ #@##########%%@%%##@@@@@@@@@@@@#%@%@@@@%@@@@@@@+@@@@%%@@@@@@@@@@%@@@@@@@@@@+==-##::+*@@%=@%@@@@@*@.@@@+%@@#.
+%%%@@@@@ @@@@@@%%#%%@%@%%%@%@%@%%%@@@@@@@+=@#@@@:=+#...-%+@@@@@@@@@@@@@@@@@@@@#-@@%*+%@%@@@@%@@@@@-@@##+%@@@@@%@+%=.%.
+%%%%**@.=@%#@*%%@@@%@#@@@%@@@@@@@@%%+%@*@@#@@@@@@@@@@@@@@@@@@@@@@@+@@@@+:**-% .+**@%%%#@#@@@@##-:-+-@@@##%@  @  @@@@+.
-%%#%%@@@@@@%@@@#@@%%*@%#%@@#*--*** #@@%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@###%@##%%#%%%%#%@@@*+++@@@%%@-:.-*@#*@+
+@@@%%#%%%@@@%%%@%@@@@@%@@+*%@@@#%@@@:++**.=.-=@@%@#%%%%%%%%#%%@@@@@#*%%%##*##%#@%%%#@*#%@@@@@@@@@%@*=-.*@@@%@@@@@@@@@=
=#%%%@@%%%%%%%@%%%#@@%@@@@@@@@@@@@@@-==*..:+==+++@@%%@@%%@@@@@%@@@@@###%#@@@@@%#%#@@%#@@%#%%@%##%%@%@@@%*=@@@@*%@@#%%#-
+%@@%%%%%%%#%#+@@@%#+*###%@@@@@@@@-:++%=@@@@@@@@@@###%%%%%%@##+@@@@@###*####%#%%%%%@@@@@@###*#%%%%%%%%%@@@%#%@@+#@@%@%+
:+==========++==--=========-=-=+:    ..:.      :%-=+++=++=----.%**##--==+==+--+=+-.#****#%+++:-=+-==+++==####*##+-=:==:




^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
||||||||||||||||||||||||||||||||
thats panzersoldat btw

]])

--// Initialization \\--
local cf=CFrame.new
local radian=math.rad
local Vec3=Vector3.new
local angles=CFrame.Angles
local ANGLES=angles
local cos=math.cos
local COS=cos
local SIN=math.sin
local sin=SIN
local rad=math.rad
local RAD=rad
local IN=Instance.new
local vt=Vector3.new
local random=math.random
local cFrame=CFrame.Angles
local Euler=CFrame.fromEulerAnglesXYZ
local euler=Euler
local colror=Color3.new
local cam=workspace.CurrentCamera
local Camera=cam
local plrs=game:GetService("Players")
local plr=plrs.LocalPlayer
local char=plr.Character
local Character=char
local hum=char:WaitForChild("Humanoid")
local root=char:WaitForChild("HumanoidRootPart")
local RootPart=root
local chinchilla=plr:GetMouse()
local mouse=chinchilla
local PlrGui=plr.PlayerGui
local Head=char:WaitForChild("Head")
local hed=char:WaitForChild("Head")
local larm=char:WaitForChild("Left Arm")
local rarm=char:WaitForChild("Right Arm")
local head=char:WaitForChild("Head")
local torso=char:WaitForChild("Torso")
local tors=char:WaitForChild("Torso")
local Torso=char:WaitForChild("Torso")
local rleg=char:WaitForChild("Right Leg")
local lleg=char:WaitForChild("Left Leg")
local attack=false
local RootCF=euler(-1.57,0,3.14)
local necko=cf(0, 1, 0, -1, -0, -0, 0, 0, 1, 0, 1, 0)
local necko2=cf(0, -0.5, 0, -1, -0, -0, 0, 0, 1, 0, 1, 0)
local lleg=char["Left Leg"]
local rleg=char["Right Leg"]
local rarm=char["Right Arm"]
local larm=char["Left Arm"]
local Anim="Idle"
local RW, LW=Instance.new("Weld"), Instance.new("Weld")
RW.Name="Right Shoulder"
RW.Part0=char.Torso 
RW.C0=cf(1.5, 0.5, 0)
RW.C1=cf(0, 0.5, 0) 
RW.Part1=char["Right Arm"] 
RW.Parent=char.Torso 
LW.Name="Left Shoulder"
LW.Part0=char.Torso 
LW.C0=cf(-1.5, 0.5, 0)
LW.C1=cf(0, 0.5, 0) 
LW.Part1=char["Left Arm"] 
LW.Parent=char.Torso 
local LH=tors["Left Hip"]
local RH=tors["Right Hip"]
local RootJoint=root.RootJoint
local cellservice=game:GetService("RunService")
necko=cf(0, 1, 0, -1, -0, -0, 0, 0, 1, 0, 1, 0)
necko2=cf(0, -0.5, 0, -1, -0, -0, 0, 0, 1, 0, 1, 0)
LHC0=cf(-1,-1,0,-0,-0,-1,0,1,0,1,0,0)
LHC1=cf(-0.5,1,0,-0,-0,-1,0,1,0,1,0,0)
RHC0=cf(1,-1,0,0,0,1,0,1,0,-1,-0,-0)
RHC1=cf(0.5,1,0,0,0,1,0,1,0,-1,-0,-0)
local attacktypecurrent=1
local introed=false
local Frame_Speed = 60 -- The frame speed for swait. 1 is automatically divided by this
local killallcooldown=false

--// Artificial HB \\--

local ArtificialHB = IN("BindableEvent", script)
ArtificialHB.Name = "Heartbeat"

script:WaitForChild("Heartbeat")

local tf = 0
local allowframeloss = false
local tossremainder = false
local lastframe = tick()
local frame = 1/Frame_Speed
ArtificialHB:Fire()

game:GetService("RunService").Heartbeat:connect(function(s, p)
	tf = tf + s
	if tf >= frame then
		if allowframeloss then
			script.Heartbeat:Fire()
			lastframe = tick()
		else
			for i = 1, math.floor(tf / frame) do
				ArtificialHB:Fire()
			end
			lastframe = tick()
		end
		if tossremainder then
			tf = 0
		else
			tf = tf - frame * math.floor(tf / frame)
		end
	end
end)

function swait(num)
	if num == 0 or num == nil then
		ArtificialHB.Event:wait()
	else
		for i = 0, num do
			ArtificialHB.Event:wait()
		end
	end
end

function QuaternionFromCFrame(cf) 
	local mx, my, mz, m00, m01, m02, m10, m11, m12, m20, m21, m22 = cf:components() 
	local trace = m00 + m11 + m22 
	if trace > 0 then 
		local s = math.sqrt(1 + trace) 
		local recip = 0.5/s 
		return (m21-m12)*recip, (m02-m20)*recip, (m10-m01)*recip, s*0.5 
	else 
		local i = 0 
		if m11 > m00 then
			i = 1
		end
		if m22 > (i == 0 and m00 or m11) then 
			i = 2 
		end 
		if i == 0 then 
			local s = math.sqrt(m00-m11-m22+1) 
			local recip = 0.5/s 
			return 0.5*s, (m10+m01)*recip, (m20+m02)*recip, (m21-m12)*recip 
		elseif i == 1 then 
			local s = math.sqrt(m11-m22-m00+1) 
			local recip = 0.5/s 
			return (m01+m10)*recip, 0.5*s, (m21+m12)*recip, (m02-m20)*recip 
		elseif i == 2 then 
			local s = math.sqrt(m22-m00-m11+1) 
			local recip = 0.5/s return (m02+m20)*recip, (m12+m21)*recip, 0.5*s, (m10-m01)*recip 
		end 
	end 
end

function QuaternionToCFrame(px, py, pz, x, y, z, w) 
	local xs, ys, zs = x + x, y + y, z + z 
	local wx, wy, wz = w*xs, w*ys, w*zs 
	local xx = x*xs 
	local xy = x*ys 
	local xz = x*zs 
	local yy = y*ys 
	local yz = y*zs 
	local zz = z*zs 
	return CFrame.new(px, py, pz,1-(yy+zz), xy - wz, xz + wy,xy + wz, 1-(xx+zz), yz - wx, xz - wy, yz + wx, 1-(xx+yy)) 
end

function QuaternionSlerp(a, b, t) 
	local cosTheta = a[1]*b[1] + a[2]*b[2] + a[3]*b[3] + a[4]*b[4] 
	local startInterp, finishInterp; 
	if cosTheta >= 0.0001 then 
		if (1 - cosTheta) > 0.0001 then 
			local theta = math.acos(cosTheta) 
			local invSinTheta = 1/math.sin(theta) 
			startInterp = math.sin((1-t)*theta)*invSinTheta 
			finishInterp = math.sin(t*theta)*invSinTheta  
		else 
			startInterp = 1-t 
			finishInterp = t 
		end 
	else 
		if (1+cosTheta) > 0.0001 then 
			local theta = math.acos(-cosTheta) 
			local invSinTheta = 1/math.sin(theta) 
			startInterp = math.sin((t-1)*theta)*invSinTheta 
			finishInterp = math.sin(t*theta)*invSinTheta 
		else 
			startInterp = t-1 
			finishInterp = t 
		end 
	end 
	return a[1]*startInterp + b[1]*finishInterp, a[2]*startInterp + b[2]*finishInterp, a[3]*startInterp + b[3]*finishInterp, a[4]*startInterp + b[4]*finishInterp 
end

function clerp(a,b,t) 
	local qa = {QuaternionFromCFrame(a)}
	local qb = {QuaternionFromCFrame(b)} 
	local ax, ay, az = a.x, a.y, a.z 
	local bx, by, bz = b.x, b.y, b.z
	local _t = 1-t
	return QuaternionToCFrame(_t*ax + t*bx, _t*ay + t*by, _t*az + t*bz,QuaternionSlerp(qa, qb, t)) 
end 

local Clerp=clerp

function rayCast(Pos, Dir, Max, Ignore)  -- Origin Position , Direction, MaxDistance , IgnoreDescendants
	return game:GetService("Workspace"):FindPartOnRay(Ray.new(Pos, Dir.unit * (Max or 999.999)), Ignore) 
end 

-------- RAINBOW LEAVE IT TO ME
local r = 255
local g = 0
local b = 0
coroutine.resume(coroutine.create(function()
	repeat swait() until introed==true
	while wait() do
		for i = 0, 254/5 do
			swait()
			g = g + 5
		end
		for i = 0, 254/5 do
			swait()
			r = r - 5
		end
		for i = 0, 254/5 do
			swait()
			b = b + 5
		end
		for i = 0, 254/5 do
			swait()
			g = g - 5
		end
		for i = 0, 254/5 do
			swait()
			r = r + 5
		end
		for i = 0, 254/5 do
			swait()
			b = b - 5
		end
	end
end))

hum.Animator.Parent=nil

local txt = Instance.new("BillboardGui", PlrGui)
txt.Adornee = Head
txt.Name = "NameDetect"
txt.Size = UDim2.new(4, 0, 1.2, 0)
txt.StudsOffset = Vector3.new(-8, 8/1.5, 0)
local text = Instance.new("TextLabel", txt)
text.Size = UDim2.new(10/2, 0, 7/2, 0)
text.FontSize = "Size8"
text.TextScaled = true
text.TextTransparency = 0
text.BackgroundTransparency = 1 
text.TextTransparency = 0
text.TextStrokeTransparency = 0
text.Font = Enum.Font.SciFi
text.TextStrokeColor3 = Color3.new(0, 0, 0)
text.TextColor3 = Color3.new(0, 0, 0)
text.Text = "ENERGY RUSH"

local CPart = IN("Part")
CPart.Anchored = true
CPart.CanCollide = false
CPart.Locked = true
CPart.Transparency = 1
local CamInterrupt = false
local TwoD = false
local TargetInfo = {nil, nil}
local Booleans = {
	CamFollow = true,
	GyroUse = true
}

function lerp(object, newCFrame, alpha)
	return object:lerp(newCFrame, alpha)
end

function CameraManager()
	if TwoD and not CamInterrupt then
		if hum.Health > 0 then
			Camera.CameraSubject = hum
			Camera.CameraType = "Scriptable"
			hum.AutoRotate = false
			if Booleans.GyroUse then
				Directer.MaxTorque = Vec3(0, math.huge, 0)
			else
				Directer.MaxTorque = Vec3(0, 0, 0)
			end
			if TargetInfo[1] ~= nil and TargetInfo[2] ~= nil then
				if Booleans.CamFollow then
					CPart.CFrame = cFrame(RootPart.Position, Vec3(TargetInfo[1].Position.X, RootPart.Position.Y, TargetInfo[1].Position.Z))
					Directer.CFrame = cFrame((RootPart.CFrame * cFrame(0, 0, 10)).p, TargetInfo[1].Position)
				else
					CPart.Position = RootPart.Position
				end
			else
				local ahead = (RootPart.CFrame * cFrame(0, 0, -3)).p
				CPart.CFrame = cFrame(RootPart.Position, Vec3(ahead.X, RootPart.Position.Y, ahead.Z))
			end
			Camera.CFrame = lerp(Camera.CFrame, CPart.CFrame * cFrame(25, 3, 0) * Euler(0, radian(90), 0), 0.2)
		else
			Camera.CameraSubject = hum
			Camera.CameraType = "Custom"
		end
	end
end

sine=0
change=1

local rainbowmode=true

function dmg(dude)
	if dude.Name ~= char then
		local bgf = Instance.new("BodyGyro",dude.Head)
		bgf.CFrame = bgf.CFrame * CFrame.fromEulerAnglesXYZ(math.rad(-90),0,0)
		local val = Instance.new("BoolValue",dude)
		val.Name = "IsHit"
		local ds = coroutine.wrap(function()
			local torso = dude:FindFirstChild'Torso' or dude:FindFirstChild'UpperTorso'
			for i = 1, 10 do
				sphereMK(1.5,2,"Add",torso.CFrame*CFrame.Angles(math.rad(math.random(-360,360)),math.rad(math.random(-360,360)),math.rad(math.random(-360,360))),1,1,25,-.01,Color3.new(r/255,g/255,b/255),0,true)
			end
			dude:WaitForChild("Head"):BreakJoints()
			wait(0.5)
			local targetted = nil
			CFuncs["Sound"].Create("rbxassetid://130113415", char, 0.5, 1)
				for i, v in pairs(dude:GetDescendants()) do
					if v:IsA("Humanoid") then
						v:Destroy()
					end
					if v:IsA("CharacterMesh") then
						v:Destroy()
					end
					if v:IsA("Model") then
						v:Destroy()
					end
					if v:IsA("Part") or v:IsA("MeshPart") then
						for x, o in pairs(v:GetChildren()) do
							if o:IsA("Decal") then
								o:Destroy()
							end
						end
						v.Material = Enum.Material.ForceField
						for i=0, 10 do
						swait()
						v.Color=colror(r/255,g/255,b/255)
						v.Transparency = v.Transparency + 0.1
						end
					end
				end
		end)
		ds()
	end
end



function FindNearestHead(Position, Distance, SinglePlayer)
	if SinglePlayer then
		return (SinglePlayer.Torso.CFrame.p - Position).magnitude < Distance
	end
	local List = {}
	for i, v in pairs(workspace:GetDescendants()) do
		if v:IsA("Model") then
			if v:findFirstChild("Head") then
				if v ~= char then
					if (v.Head.CFrame.p - Position).magnitude <= Distance then
						table.insert(List, v)
					end 
				end 
			end 
		end 
	end
	return List
end
function sphereMKCharge(bonuspeed,FastSpeed,type,pos,x1,y1,z1,value,color,outerpos)
	local type = type
	local rng = Instance.new("Part", char)
	rng.Anchored = true
	rng.BrickColor = color
	rng.CanCollide = false
	rng.FormFactor = 3
	rng.Name = "Ring"
	rng.Material = "Neon"
	rng.Size = Vector3.new(1, 1, 1)
	rng.Transparency = 1
	rng.TopSurface = 0
	rng.BottomSurface = 0
	rng.CFrame = pos
	rng.CFrame = rng.CFrame + rng.CFrame.lookVector*outerpos
	local rngm = Instance.new("SpecialMesh", rng)
	rngm.MeshType = "Sphere"
	rngm.Scale = vt(x1,y1,z1)
	if rainbowmode == true then
		rng.Color = Color3.new(r/255,g/255,b/255)
	end
	local scaler2 = 1
	local speeder = FastSpeed
	if type == "Add" then
		scaler2 = 1*value
	elseif type == "Divide" then
		scaler2 = 1/value
	end
	coroutine.resume(coroutine.create(function()
		for i = 0,10/bonuspeed,0.1 do
			swait()
			if rainbowmode == true then
				rng.Color = Color3.new(r/255,g/255,b/255)
			end
			if type == "Add" then
				scaler2 = scaler2 - 0.01*value/bonuspeed
			elseif type == "Divide" then
				scaler2 = scaler2 - 0.01/value*bonuspeed
			end
			speeder = speeder - 0.01*FastSpeed*bonuspeed
			rng.CFrame = rng.CFrame + rng.CFrame.lookVector*speeder*bonuspeed
			rng.Transparency = rng.Transparency - 0.01*bonuspeed
			rngm.Scale = rngm.Scale + Vector3.new(scaler2*bonuspeed, scaler2*bonuspeed, 0)
		end
		rng:Destroy()
	end))
end



local kan=Instance.new("Sound",char);
kan.Name="theme";
kan.Pitch=1;
kan.Looped=true;
kan.SoundId="rbxassetid://1836465431";
kan:Play()

function PixelBlockNeg(bonuspeed,FastSpeed,type,pos,x1,y1,z1,value,color,outerpos)
	local type = type
	local rng = Instance.new("Part", char)
	rng.Anchored = true
	rng.BrickColor = color
	rng.CanCollide = false
	rng.FormFactor = 3
	rng.Name = "Ring"
	rng.Material = "Neon"
	rng.Size = Vector3.new(1, 1, 1)
	rng.Transparency = 0
	rng.TopSurface = 0
	rng.BottomSurface = 0
	rng.CFrame = pos
	rng.CFrame = rng.CFrame + rng.CFrame.lookVector*outerpos
	local rngm = Instance.new("SpecialMesh", rng)
	rngm.MeshType = "Brick"
	rngm.Scale = vt(x1,y1,z1)
	if rainbowmode == true then
		rng.Color = Color3.new(r/255,g/255,b/255)
	end
	local scaler2 = 0
	local speeder = FastSpeed/10
	if type == "Add" then
		scaler2 = 1*value
	elseif type == "Divide" then
		scaler2 = 1/value
	end
	coroutine.resume(coroutine.create(function()
		for i = 0,10/bonuspeed,0.1 do
			swait()
			if rainbowmode == true then
				rng.Color = Color3.new(r/255,g/255,b/255)
			end
			if type == "Add" then
				scaler2 = scaler2 - 0.01*value/bonuspeed
			elseif type == "Divide" then
				scaler2 = scaler2 - 0.01/value*bonuspeed
			end
			speeder = speeder + 0.01*FastSpeed*bonuspeed/10
			rng.CFrame = rng.CFrame + rng.CFrame.lookVector*speeder*bonuspeed
			rngm.Scale = rngm.Scale - Vector3.new(scaler2*bonuspeed, scaler2*bonuspeed, scaler2*bonuspeed)
		end
		rng:Destroy()
	end))
end

local Create = function(instance,properties)
	local inst = Instance.new(instance)
	if(properties)then
		for i,v in next, properties do
			pcall(function() inst[i] = v end)
		end
	end
	return inst;
end

CFuncs = {	
	["Part"] = {
		Create = function(Parent, Material, Reflectance, Transparency, BColor, Name, Size)
			local Part = Create("Part",{
				Parent = Parent,
				Reflectance = Reflectance,
				Transparency = Transparency,
				CanCollide = false,
				Locked = true,
				BrickColor = BrickColor.new(tostring(BColor)),
				Name = Name,
				Size = Size,
				Material = Material,
			})
			RemoveOutlines(Part)
			return Part
		end;
	};

	["Mesh"] = {
		Create = function(Mesh, Part, MeshType, MeshId, OffSet, Scale)
			local Msh = Create(Mesh,{
				Parent = Part,
				Offset = OffSet,
				Scale = Scale,
			})
			if Mesh == "SpecialMesh" then
				Msh.MeshType = MeshType
				Msh.MeshId = MeshId
			end
			return Msh
		end;
	};

	["Weld"] = {
		Create = function(Parent, Part0, Part1, C0, C1)
			local Weld = Create("Weld",{
				Parent = Parent,
				Part0 = Part0,
				Part1 = Part1,
				C0 = C0,
				C1 = C1,
			})
			return Weld
		end;
	};

	["Sound"] = {
		Create = function(id, par, vol, pit) 
			coroutine.resume(coroutine.create(function()
				local S = Create("Sound",{
					Volume = vol,
					Name = "EffectSoundo",
					Pitch = pit or 1,
					SoundId = id,
					Parent = par or workspace,
				})
				wait() 
				S:play() 
				game:GetService("Debris"):AddItem(S, 10)
			end))
		end;
	};

	["TimeSound"] = {
		Create = function(id, par, vol, pit, timepos) 
			coroutine.resume(coroutine.create(function()
				local S = Create("Sound",{
					Volume = vol,
					Name = "EffectSoundo",
					Pitch = pit or 1,
					SoundId = id,
					TimePosition = timepos,
					Parent = par or workspace,
				})
				wait() 
				S:play() 
				game:GetService("Debris"):AddItem(S, 10)
			end))
		end;
	};
	["EchoSound"] = {
		Create = function(id, par, vol, pit, timepos,delays,echodelay,fedb,dryl) 
			coroutine.resume(coroutine.create(function()
				local Sas = Create("Sound",{
					Volume = vol,
					Name = "EffectSoundo",
					Pitch = pit or 1,
					SoundId = id,
					TimePosition = timepos,
					Parent = par or workspace,
				})
				local E = Create("EchoSoundEffect",{
					Delay = echodelay,
					Name = "Echo",
					Feedback = fedb,
					DryLevel = dryl,
					Parent = Sas,
				})
				wait() 
				Sas:play() 
				game:GetService("Debris"):AddItem(Sas, delays)
			end))
		end;
	};

	["LongSound"] = {
		Create = function(id, par, vol, pit) 
			coroutine.resume(coroutine.create(function()
				local S = Create("Sound",{
					Volume = vol,
					Pitch = pit or 1,
					SoundId = id,
					Parent = par or workspace,
				})
				wait() 
				S:play() 
				game:GetService("Debris"):AddItem(S, 60)
			end))
		end;
	};

	["ParticleEmitter"] = {
		Create = function(Parent, Color1, Color2, LightEmission, Size, Texture, Transparency, ZOffset, Accel, Drag, LockedToPart, VelocityInheritance, EmissionDirection, Enabled, LifeTime, Rate, Rotation, RotSpeed, Speed, VelocitySpread)
			local fp = Create("ParticleEmitter",{
				Parent = Parent,
				Color = ColorSequence.new(Color1, Color2),
				LightEmission = LightEmission,
				Size = Size,
				Texture = Texture,
				Transparency = Transparency,
				ZOffset = ZOffset,
				Acceleration = Accel,
				Drag = Drag,
				LockedToPart = LockedToPart,
				VelocityInheritance = VelocityInheritance,
				EmissionDirection = EmissionDirection,
				Enabled = Enabled,
				Lifetime = LifeTime,
				Rate = Rate,
				Rotation = Rotation,
				RotSpeed = RotSpeed,
				Speed = Speed,
				VelocitySpread = VelocitySpread,
			})
			return fp
		end;
	};

	CreateTemplate = {

	};
}

function sphere(bonuspeed,type,pos,scale,value,color,heart,invert,notaffectbychaosrainbow)
	local type = type
	local rng = Instance.new("Part", char)
	rng.Anchored = true
	rng.BrickColor = color
	rng.CanCollide = false
	rng.FormFactor = 3
	rng.Name = "Ring"
	rng.Material = "Neon"
	rng.Size = Vector3.new(1, 1, 1)
	rng.Transparency = 0
	rng.TopSurface = 0
	rng.BottomSurface = 0
	rng.CFrame = pos
	local rngm = Instance.new("SpecialMesh", rng)
	rngm.MeshType = "Sphere"


	if(heart)then
		rngm.MeshType = Enum.MeshType.FileMesh
		rngm.MeshId = "rbxassetid://105992239"
		rngm.Offset = Vector3.new(0,0,-.25)
	end
	rngm.Scale = scale
	if rainbowmode == true then
		rng.Color = Color3.new(r/255,g/255,b/255)
	end
	local scaler2 = 1
	if type == "Add" then
		scaler2 = 1*value
	elseif type == "Divide" then
		scaler2 = 1/value
	end
	coroutine.resume(coroutine.create(function()
		for i = 0,10/bonuspeed,0.1 do
			swait()
			if rainbowmode == true then
				rng.Color = Color3.new(r/255,g/255,b/255)
			end
			if type == "Add" then
				scaler2 = scaler2 - 0.01*value/bonuspeed
			elseif type == "Divide" then
				scaler2 = scaler2 - 0.01/value*bonuspeed
			end
			rng.Transparency = rng.Transparency + 0.01*bonuspeed
			if(invert)then
				if(heart)then 
					rngm.Scale = rngm.Scale - Vector3.new(scaler2*bonuspeed, scaler2*bonuspeed, 0) 
				else 
					rngm.Scale = rngm.Scale - Vector3.new(scaler2*bonuspeed, scaler2*bonuspeed, scaler2*bonuspeed) 
				end
			else
				if(heart)then 
					rngm.Scale = rngm.Scale + Vector3.new(scaler2*bonuspeed, scaler2*bonuspeed, 0) 
				else 
					rngm.Scale = rngm.Scale + Vector3.new(scaler2*bonuspeed, scaler2*bonuspeed, scaler2*bonuspeed) 
				end
			end
			rng.CFrame = pos
		end
		rng:Destroy()
	end))
end

function sphereMK(bonuspeed,FastSpeed,type,pos,x1,y1,z1,value,color,outerpos)
	local type = type
	local rng = Instance.new("Part", char)
	rng.Anchored = true
	rng.Color = color
	rng.CanCollide = false
	rng.FormFactor = 3
	rng.Name = "Ring"
	rng.Material = "Neon"
	rng.Size = Vector3.new(1, 1, 1)
	rng.Transparency = 0
	rng.TopSurface = 0
	rng.BottomSurface = 0
	rng.CFrame = pos
	rng.CFrame = rng.CFrame + rng.CFrame.lookVector*outerpos
	local rngm = Instance.new("SpecialMesh", rng)
	rngm.MeshType = "Sphere"
	rngm.Scale = vt(x1,y1,z1)
	if rainbowmode == true then
		rng.Color = Color3.new(r/255,g/255,b/255)
	end
	local scaler2 = 1
	local speeder = FastSpeed
	if type == "Add" then
		scaler2 = 1*value
	elseif type == "Divide" then
		scaler2 = 1/value
	end
	coroutine.resume(coroutine.create(function()
		for i = 0,10/bonuspeed,0.1 do
			swait()
			if type == "Add" then
				scaler2 = scaler2 - 0.01*value/bonuspeed
			elseif type == "Divide" then
				scaler2 = scaler2 - 0.01/value*bonuspeed
			end
			if rainbowmode == true then
				rng.Color = Color3.new(r/255,g/255,b/255)
			end
			speeder = speeder - 0.01*FastSpeed*bonuspeed
			rng.CFrame = rng.CFrame + rng.CFrame.lookVector*speeder*bonuspeed
			rng.Transparency = rng.Transparency + 0.01*bonuspeed
			rngm.Scale = rngm.Scale + Vector3.new(scaler2*bonuspeed, scaler2*bonuspeed, 0)
		end
		rng:Destroy()
	end))
end



function PixelBlock(bonuspeed,FastSpeed,type,pos,x1,y1,z1,value,color,outerpos,heart,invert)
	local type = type
	local rng = Instance.new("Part", char)
	rng.Anchored = true
	rng.BrickColor = color
	rng.CanCollide = false
	rng.FormFactor = 3
	rng.Name = "Ring"
	rng.Material = "Neon"
	rng.Size = Vector3.new(1, 1, 1)
	rng.Transparency = 0
	rng.TopSurface = 0
	rng.BottomSurface = 0
	rng.CFrame = pos
	rng.CFrame = rng.CFrame + rng.CFrame.lookVector*outerpos
	local rngm = Instance.new("SpecialMesh", rng)
	rngm.MeshType = "Brick"
	if(heart)then
		rngm.MeshType = Enum.MeshType.FileMesh
		rngm.MeshId = "rbxassetid://105992239"
		rngm.Offset = Vector3.new(0,0,-.25)
	end
	rngm.Scale = vt(x1,y1,z1)
	if rainbowmode == true then
		rng.Color = Color3.new(r/255,g/255,b/255)
	end
	local scaler2 = 1
	local speeder = FastSpeed/10
	if type == "Add" then
		scaler2 = 1*value
	elseif type == "Divide" then
		scaler2 = 1/value
	end
	coroutine.resume(coroutine.create(function()
		for i = 0,10/bonuspeed,0.1 do
			swait()
			if rainbowmode == true then
				rng.Color = Color3.new(r/255,g/255,b/255)
			end
			if type == "Add" then
				scaler2 = scaler2 - 0.01*value/bonuspeed
			elseif type == "Divide" then
				scaler2 = scaler2 - 0.01/value*bonuspeed
			end
			speeder = speeder - 0.01*FastSpeed*bonuspeed/10
			if(invert)then rng.CFrame = rng.CFrame - rng.CFrame.lookVector*speeder*bonuspeed else rng.CFrame = rng.CFrame + rng.CFrame.lookVector*speeder*bonuspeed end
			--rng.Transparency = rng.Transparency + 0.01*bonuspeed
			rngm.Scale = rngm.Scale - Vector3.new(scaler2*bonuspeed, scaler2*bonuspeed, scaler2*bonuspeed)
		end
		rng:Destroy()
	end))
end

--// Char setup \\--

local modellringy=Instance.new("Model",char);
modellringy.Name="band";
local ringycolor=Instance.new("Part",modellringy);
ringycolor.Size=Vector3.new(1.12,0.12,1.12);
ringycolor.Anchored=false;
ringycolor.CanCollide=false;
ringycolor.Transparency=0;
ringycolor.Material=Enum.Material.Neon;
ringycolor.Color=colror(0,0,0)
local ringycolorweld=Instance.new("Weld",ringycolor);
ringycolorweld.Part0=rarm;
ringycolorweld.Part1=ringycolor;
ringycolorweld.C0=CFrame.new(0,-0.6,0);
local ringycolorjunior=Instance.new("Part",modellringy);
ringycolorjunior.Size=Vector3.new(1.11,0.17,1.11);
ringycolorjunior.Anchored=false;
ringycolorjunior.CanCollide=false;
ringycolorjunior.Transparency=0;
ringycolorjunior.Material=Enum.Material.Granite;
local ringycolorjuniorweld=Instance.new("Weld",ringycolorjunior);
ringycolorjuniorweld.Part0=ringycolor;
ringycolorjuniorweld.Part1=ringycolorjunior;
local ringy2=Instance.new("Part",modellringy);
ringy2.Size=Vector3.new(1.1,0.22,1.1);
ringy2.Anchored=false;
ringy2.CanCollide=false;
ringy2.Transparency=0;
ringy2.Material=Enum.Material.Granite;
ringy2.Color=colror(0,0,0)
local ringy2weld=Instance.new("Weld",ringy2);
ringy2weld.Part0=ringycolor;
ringy2weld.Part1=ringy2;
local ringy3=Instance.new("Part",modellringy);
ringy3.Size=Vector3.new(1.07,0.27,1.07);
ringy3.Anchored=false;
ringy3.CanCollide=false;
ringy3.Transparency=0;
ringy3.Material=Enum.Material.Glass;
ringy3.Color=colror(0,0,0)
local ringy3weld=Instance.new("Weld",ringy3);
ringy3weld.Part0=ringy2;
ringy3weld.Part1=ringy3;
local cannonbase=Instance.new("Part",modellringy);
cannonbase.Size=Vector3.new(1.05,1.42,1.05);
cannonbase.Anchored=false;
cannonbase.CanCollide=false;
cannonbase.Transparency=0;
cannonbase.BrickColor=BrickColor.new("Really black")
cannonbase.Material=Enum.Material.Granite;
local cannonbaseweld=Instance.new("Weld",cannonbase);
cannonbaseweld.Part0=larm;
cannonbaseweld.Part1=cannonbase;
cannonbaseweld.C0=CFrame.new(0,-0.417,0);
local in1=Instance.new("Part",modellringy);
in1.Size=Vector3.new(0.3467,0.677,0.041);
in1.Anchored=false;
in1.CanCollide=false;
in1.Transparency=0;
in1.Material=Enum.Material.Glass;
in1.BrickColor=BrickColor.new("Really black")
local in1weld=Instance.new("Weld",in1);
in1weld.Part0=cannonbase;
in1weld.Part1=in1;
in1.Rotation=Vector3.new(-20.068,0,0)
in1weld.C0=CFrame.new(0,-0.088,-0.628)
local in2=Instance.new("Part",modellringy);
in2.Size=Vector3.new(0.072, 0.677, 0.212);
in2.Anchored=false;
in2.CanCollide=false;
in2.Transparency=0;
in2.Material=Enum.Material.Glass;
in2.BrickColor=BrickColor.new("Really black")
local in2weld=Instance.new("Weld",in2);
in2weld.Part0=cannonbase;
in2weld.Part1=in2;
in2weld.C0=CFrame.new(-0.137, -0.044, -0.509)
in2.Rotation=Vector3.new(-20.068,0,0)
local in3=Instance.new("Part",modellringy);
in3.Size=Vector3.new(0.072, 0.677, 0.212);
in3.Anchored=false;
in3.CanCollide=false;
in3.Transparency=0;
in3.Material=Enum.Material.Glass;
in3.BrickColor=BrickColor.new("Really black")
local in3weld=Instance.new("Weld",in3);
in3weld.Part0=cannonbase;
in3weld.Part1=in3;
in3weld.C0=CFrame.new(0.137, -0.044, -0.509)
in3.Rotation=Vector3.new(-20.068,0,0)
local cnglow1=Instance.new("Part",modellringy);
cnglow1.Size=Vector3.new(0.147, 1, 0.527);
cnglow1.Anchored=false;
cnglow1.CanCollide=false;
cnglow1.Transparency=0;
cnglow1.Material=Enum.Material.Neon;
cnglow1.Color=colror(0,0,0)
local cnglow1mes=Instance.new("SpecialMesh",cnglow1);
cnglow1mes.MeshType=Enum.MeshType.Cylinder;
local cnglow1weld=Instance.new("Weld",cnglow1);
cnglow1weld.Part0=cannonbase;
cnglow1weld.Part1=cnglow1;
cnglow1weld.C0=CFrame.new(0, -0.657, 0)
cnglow1.Rotation=Vector3.new(0, 0, 90)
local cnglow2=Instance.new("Part",modellringy);
cnglow2.Size=Vector3.new(0.147, 1.497, 1.11);
cnglow2.Anchored=false;
cnglow2.CanCollide=false;
cnglow2.Transparency=0;
cnglow2.Material=Enum.Material.Neon;
cnglow2.Color=colror(0,0,0)
local cnglow2weld=Instance.new("Weld",cnglow2);
cnglow2weld.Part0=cannonbase;
cnglow2weld.Part1=cnglow2;
cnglow2weld.C0=CFrame.new(-0, 0.012, 0)
local cnglow3=Instance.new("Part",modellringy);
cnglow3.Size=Vector3.new(1.11, 1.497, 0.147);
cnglow3.Anchored=false;
cnglow3.CanCollide=false;
cnglow3.Transparency=0;
cnglow3.Material=Enum.Material.Neon;
cnglow3.Color=colror(0,0,0)
local cnglow3weld=Instance.new("Weld",cnglow3);
cnglow3weld.Part0=cannonbase;
cnglow3weld.Part1=cnglow3;
cnglow3weld.C0=CFrame.new(0, 0.012, 0)
local stabliz1=Instance.new("Part",modellringy);
stabliz1.Size=Vector3.new(0.139, 0.638, 0.041);
stabliz1.Anchored=false;
stabliz1.CanCollide=false;
stabliz1.Transparency=0;
stabliz1.Material=Enum.Material.Glass;
stabliz1.BrickColor=BrickColor.new("Really black")
local stabliz1weld=Instance.new("Weld",stabliz1);
stabliz1weld.Part0=cannonbase;
stabliz1weld.Part1=stabliz1;
stabliz1weld.C0=CFrame.new(0, -0.909, -0.328)
stabliz1.Rotation=Vector3.new(-20.068, 0, 0)
local stabliz2=Instance.new("Part",modellringy);
stabliz2.Size=Vector3.new(0.139, 0.638, 0.041);
stabliz2.Anchored=false;
stabliz2.CanCollide=false;
stabliz2.Transparency=0;
stabliz2.Material=Enum.Material.Glass;
stabliz2.BrickColor=BrickColor.new("Really black")
local stabliz2weld=Instance.new("Weld",stabliz2);
stabliz2weld.Part0=cannonbase;
stabliz2weld.Part1=stabliz2;
stabliz2weld.C0=CFrame.new(-0, -0.926, 0.262)
stabliz2.Rotation=Vector3.new(20.068, 180, 0)
larm.Material=Enum.Material.ForceField
local core=Instance.new("Part",modellringy);
core.Size=Vector3.new(0.5, 0.5, 0.5);
core.Anchored=false;
core.CanCollide=false;
core.Transparency=0;
core.Material=Enum.Material.Neon;
core.Color=colror(0,0,0)
local coremes=Instance.new("SpecialMesh",core);
coremes.MeshType=Enum.MeshType.Sphere;
local coreweld=Instance.new("Weld",core);
coreweld.Part0=larm;
coreweld.Part1=core;
coreweld.C0=CFrame.new(0, 0.65, 0)
local orbbulletposthingyidk=Instance.new("Part",modellringy);
orbbulletposthingyidk.Size=Vector3.new(0.5, 0.5, 0.5);
orbbulletposthingyidk.Anchored=false;
orbbulletposthingyidk.CanCollide=false;
orbbulletposthingyidk.Transparency=1;
orbbulletposthingyidk.Material=Enum.Material.Neon;
orbbulletposthingyidk.Color=colror(0,0,0)
local orbbulletposmes=Instance.new("SpecialMesh",orbbulletposthingyidk);
orbbulletposmes.MeshType=Enum.MeshType.Sphere;
local orbbulletposweld=Instance.new("Weld",orbbulletposthingyidk);
orbbulletposweld.Part0=cnglow1;
orbbulletposweld.Part1=orbbulletposthingyidk;
orbbulletposweld.C0=CFrame.new(-0.5, 0, 0)

function chatfunc(text,color)
	local chat = coroutine.wrap(function()
		if char:FindFirstChild("TalkingBillBoard")~= nil then
			char:FindFirstChild("TalkingBillBoard"):destroy()
		end
		local naeeym2 = Instance.new("BillboardGui",char)
		naeeym2.Size = UDim2.new(0,100,0,40)
		naeeym2.StudsOffset = Vector3.new(0,3,0)
		naeeym2.Adornee = char.Head
		naeeym2.Name = "TalkingBillBoard"
		local tecks2 = Instance.new("TextLabel",naeeym2)
		tecks2.BackgroundTransparency = 1
		tecks2.BorderSizePixel = 0
		tecks2.Text = ""
		tecks2.Font = "SciFi"
		tecks2.TextSize = 30
		tecks2.TextStrokeTransparency = 0
		tecks2.TextColor3 = color
		tecks2.TextStrokeColor3 = Color3.new(0,0,0)
		tecks2.Size = UDim2.new(1,0,0.5,0)
		local tecks3 = Instance.new("TextLabel",naeeym2)
		tecks3.BackgroundTransparency = 1
		tecks3.BorderSizePixel = 0
		tecks3.Text = ""
		tecks3.Font = "SciFi"
		tecks3.TextSize = 30
		tecks3.TextStrokeTransparency = 0
		tecks3.TextColor3 = Color3.new(0,0,0)
		tecks3.TextStrokeColor3 = color
		tecks3.Size = UDim2.new(1,0,0.5,0)
		for i = 1,string.len(text),1 do
			CFuncs["Sound"].Create("rbxassetid://274118116", char, 0.25, 0.115)
			tecks2.Text = string.sub(text,1,i)
			tecks3.Text = string.sub(text,1,i)
			swait(1)
		end
		wait(1)
		local randomrot = math.random(1,2)
		if randomrot == 1 then
			for i = 1, 50 do
				swait()
				tecks2.Rotation = tecks2.Rotation - .75
				tecks2.TextStrokeTransparency = tecks2.TextStrokeTransparency +.04
				tecks2.TextTransparency = tecks2.TextTransparency + .04
				tecks3.Rotation = tecks2.Rotation + .75
				tecks3.TextStrokeTransparency = tecks2.TextStrokeTransparency +.04
				tecks3.TextTransparency = tecks2.TextTransparency + .04
			end
		elseif randomrot == 2 then
			for i = 1, 50 do
				swait()
				tecks2.Rotation = tecks2.Rotation + .75
				tecks2.TextStrokeTransparency = tecks2.TextStrokeTransparency +.04
				tecks2.TextTransparency = tecks2.TextTransparency + .04
				tecks3.Rotation = tecks2.Rotation - .75
				tecks3.TextStrokeTransparency = tecks2.TextStrokeTransparency +.04
				tecks3.TextTransparency = tecks2.TextTransparency + .04
			end
		end
		naeeym2:Destroy()
	end)
	chat()
end

function ShowDamage(Pos, tex, Time, Color)
	local Rate = 0.03333333333333333
	local Pos = Pos or Vector3.new(0, 0, 0)
	local Text = tex or ""
	local Time = Time or 2
	local Color = Color or Color3.new(1, 0, 1)
	local EffectPart = CreatePart(workspace, "SmoothPlastic", 0, 1, BrickColor.new(Color), "Effect", Vector3.new(0, 0, 0))
	EffectPart.Anchored = true
	local BillboardGui = Create("BillboardGui",{
		Size = UDim2.new(3, 0, 3, 0),
		Adornee = EffectPart,
		Parent = EffectPart
	})
	local TextLabel = Create("TextLabel",{
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 1, 0),
		Text = Text,
		TextColor3 = Color,
		TextScaled = true,
		Font = Enum.Font.ArialBold,
		Parent = BillboardGui
	})
	game.Debris:AddItem(EffectPart, Time + 0.1)
	EffectPart.Parent = game:GetService("Workspace")
	delay(0, function()
		local Frames = Time / Rate
		for Frame = 1, Frames do
			wait(Rate)
			local Percent = Frame / Frames
			EffectPart.CFrame = CFrame.new(Pos) + Vector3.new(0, Percent, 0)
			TextLabel.TextTransparency = Percent
		end
		if EffectPart and EffectPart.Parent then
			EffectPart:Destroy()
		end
	end)
end

function RemoveOutlines(part)
	part.TopSurface, part.BottomSurface, part.LeftSurface, part.RightSurface, part.FrontSurface, part.BackSurface = 10, 10, 10, 10, 10, 10
end

function CreatePart(parry, Material, Reflectance, Transparency, BColor, Name, Size)
	local Part = Instance.new("Part")
	Part.Parent = parry
	Part.Reflectance = Reflectance
	Part.Transparency = Transparency
	Part.CanCollide = false
	Part.Locked = true
	Part.BrickColor = BrickColor.new(tostring(BColor))
	Part.Name = Name
	Part.Size = Size
	Part.Material = Material
	Part.CustomPhysicalProperties = PhysicalProperties.new(0.001, 0.001, 0.001, 0.001, 0.001)
	RemoveOutlines(Part)
	return Part
end

function Damagefunc(Part, hit, minim, maxim, knockback, Type, Property, Delay, HitSound, HitPitch)
	if hit.Parent == nil then
		return
	end
	local h = hit.Parent:FindFirstChildOfClass("Humanoid")
	for _, v in pairs(hit.Parent:children()) do
		if v:IsA("Humanoid") then
			h = v
		end
	end
	if h ~= nil and hit.Parent.Name ~= Character.Name and hit.Parent:FindFirstChild("Head") ~= nil then
		if hit.Parent:findFirstChild("DebounceHit") ~= nil and hit.Parent.DebounceHit.Value == true then
			return
		end
		local c = Instance.new("ObjectValue")
		c.Name = "creator"
		c.Value = game:GetService("Players").LocalPlayer
		c.Parent = h

		game:GetService("Debris"):AddItem(c, 0.5)
		if HitSound ~= nil and HitPitch ~= nil then
			CFuncs["EchoSound"].Create(HitSound, char, 1.5, 1,0,10,0.15,0.5,1)
		end
		local Damage = math.random(minim, maxim)
		local blocked = false
		local block = hit.Parent:findFirstChild("Block")
		if block ~= nil and block.className == "IntValue" and block.Value > 0 then
			blocked = true
			block.Value = block.Value - 1
			print(block.Value)
		end
		if blocked == false then
			local HitHealth = h.Health
			h.Health = h.Health - Damage
			if HitHealth ~= h.Health and HitHealth ~= 0 and 0 >= h.Health and h.Parent.Name ~= "Hologram" then
				print("gained kill")
				dmg(hit.Parent)
			end
			ShowDamage(Part.CFrame * CFrame.new(0, 0, Part.Size.Z / 2).Position + Vector3.new(0, 1.5, 0), -Damage, 1.5, colror(r/255,g/255,b/255))
		else
			h.Health = h.Health - Damage / 2
			ShowDamage(Part.CFrame * CFrame.new(0, 0, Part.Size.Z / 2).Position + Vector3.new(0, 1.5, 0), -Damage, 1.5, colror(r/255,g/255,b/255))
		end
		local debounce = Instance.new("BoolValue")
		debounce.Name = "DebounceHit"
		debounce.Parent = hit.Parent
		debounce.Value = true

		game:GetService("Debris"):AddItem(debounce, Delay)
		c = Instance.new("ObjectValue")
		c.Name = "creator"
		c.Value = plr
		c.Parent = h
		game:GetService("Debris"):AddItem(c, 0.5)
	end
end
function MagniDamage(Part, magni, mindam, maxdam, knock, Type)
	for _, c in pairs(workspace:GetDescendants()) do
		local hum = c:findFirstChildOfClass("Humanoid")
		if hum ~= nil then
			local head = c:FindFirstChild("Head")
			if head ~= nil then
				local targ = head.Position - Part.Position
				local mag = targ.magnitude
				if magni >= mag and c.Name ~= plr.Name then
					Damagefunc(head, head, mindam, maxdam, knock, Type, RootPart, 0.1, "rbxassetid://231917784", 1)
				end
			end
		end
	end
end

function FaceMouse()
	local Cam = workspace.CurrentCamera
	return {
		CFrame.new(char.Torso.Position, Vector3.new(mouse.Hit.p.x, char.Torso.Position.y, mouse.Hit.p.z)),
		Vector3.new(mouse.Hit.p.x, mouse.Hit.p.y, mouse.Hit.p.z)
	}
end

--// Attacks \\--

function intro()
	larm.Color=colror(0,0,0)
	attack = true
	hum.WalkSpeed=0
	hum.JumpPower=0
	CFuncs["Sound"].Create("rbxassetid://7148330411",ringycolor,5,1)
	for i=1,100 do
		swait()
		sphereMKCharge(5,-0.25,"Add",ringycolor.CFrame*CFrame.Angles(math.rad(math.random(-360,360)),math.rad(math.random(-360,360)),math.rad(math.random(-360,360))),0.5,0.5,5,-0.005,BrickColor.new("White"),10)
		PixelBlockNeg(2,1,"Add",ringycolor.CFrame*CFrame.Angles(math.rad(math.random(-360,360)),math.rad(math.random(-360,360)),math.rad(math.random(-360,360))),1,1,1,0.01,BrickColor.new("White"),0)
		RH.C0=clerp(RH.C0,cf(1,-1 - 0.05 * math.cos(sine / 28),0)*angles(math.rad(0),math.rad(90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(sine / 34))),.1)
		LH.C0=clerp(LH.C0,cf(-1,-1 - 0.05 * math.cos(sine / 28),0)*angles(math.rad(0),math.rad(-90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(sine / 34))),.1)
		RootJoint.C0=clerp(RootJoint.C0,RootCF*cf(0,0,0 + 0.05 * math.cos(sine / 28))*angles(math.rad(0 - 1 * math.cos(sine / 34)),math.rad(0),math.rad(0)),.1)
		Torso.Neck.C0=clerp(Torso.Neck.C0,necko*angles(math.rad(5 - 2.5 * math.cos(sine / 28)),math.rad(0),math.rad(0)),.1)
		RW.C0=clerp(RW.C0,cf(1.5,0.5,0)*angles(math.rad(180),math.rad(20),math.rad(0)),.1)
		LW.C0=clerp(LW.C0,cf(-1.45,0.5 + 0.1 * math.cos(sine / 25),0)*angles(math.rad(-5),math.rad(0),math.rad(-25)),.1)
	end
	CFuncs["Sound"].Create("rbxassetid://206082327", root, 2.5,1)
	CFuncs["Sound"].Create("rbxassetid://847061203", root, 5,1)
	CFuncs["Sound"].Create("rbxassetid://239000203", root, 2.5,1)
	CFuncs["Sound"].Create("rbxassetid://579687077", root, 2.5,0.75)
	sphere(2.5,"Add",root.CFrame,vt(0,0,0),1,BrickColor.new("White"))
	for i = 0, 49 do
		PixelBlock(1,math.random(1,20),"Add",root.CFrame*CFrame.Angles(math.rad(math.random(-360,360)),math.rad(math.random(-360,360)),math.rad(math.random(-360,360))),2,2,2,0.04,BrickColor.new("White"),0)
	end
	for i = 0,3,0.1 do
		sphereMK(2.5,-1,"Add",root.CFrame*CFrame.Angles(math.rad(math.random(-360,360)),math.rad(math.random(-360,360)),math.rad(math.random(-360,360))),2.5,2.5,25,-0.025,BrickColor.new("White").Color,0)
	end
	attack = false
	hum.WalkSpeed=16
	hum.JumpPower=50
	introed=true
	CFuncs["Sound"].Create("rbxassetid://130976109",ringycolor,5,1)
	CFuncs["Sound"].Create("rbxassetid://140479190682021",ringycolor,5,1)
	CFuncs["Sound"].Create("rbxassetid://7649721525",hed,5,1)
end

if not introed then
	intro()
end

function lilpunch()
	attack = true
	for i = 0,1,0.1 do
		swait()
		RootJoint.C0 = clerp(RootJoint.C0,RootCF*cf(0,0,0)* angles(math.rad(20),math.rad(0),math.rad(-40)),0.2)
		Torso.Neck.C0 = clerp(Torso.Neck.C0,necko *angles(math.rad(0),math.rad(0),math.rad(40)),.2)
		RW.C0 = clerp(RW.C0, CFrame.new(1.45, 0.5, 0) * angles(math.rad(90), math.rad(0), math.rad(-40)), 0.2)
	end
	CFuncs["Sound"].Create("rbxassetid://200632136", root, 1, 1.1)

	local hitb = Instance.new("Part", char)
	hitb.Anchored = true
	hitb.CanCollide = false
	hitb.FormFactor = 3
	hitb.Name = "Ring"
	hitb.Material = "Neon"
	hitb.Size = Vector3.new(1, 1, 1)
	hitb.Transparency = 1
	hitb.TopSurface = 0
	hitb.BottomSurface = 0
	hitb.CFrame = root.CFrame + root.CFrame.lookVector*2
	MagniDamage(hitb, 3, 10,30, 0, "Normal")
	hitb:Destroy()
	for i = 0,1,0.1 do
		swait()
		RootJoint.C0 = clerp(RootJoint.C0,RootCF*cf(0,0,0)* angles(math.rad(-5),math.rad(0),math.rad(70)),0.4)
		Torso.Neck.C0 = clerp(Torso.Neck.C0,necko *angles(math.rad(20),math.rad(0),math.rad(-70)),.4)
		RW.C0 = clerp(RW.C0, CFrame.new(1.45, 0.5, 0) * angles(math.rad(90), math.rad(0), math.rad(70)), 0.4)
	end

	attack = false
end

function teleport()
	attack = true
	hum.WalkSpeed = 0
	hum.JumpPower = 0
	CFuncs["Sound"].Create("rbxassetid://136007472", root, 2.5, 1.25)
	for i=1,45 do
		swait()
		root.CFrame=FaceMouse()[1]
		sphereMKCharge(5,-0.25,"Add",orbbulletposthingyidk.CFrame*CFrame.Angles(math.rad(math.random(-360,360)),math.rad(math.random(-360,360)),math.rad(math.random(-360,360))),0.5,0.5,5,-0.005,BrickColor.new("White"),10)
		sphere(0,"Add",orbbulletposthingyidk.CFrame,Vector3.new(.5,.5,.5),1,BrickColor.new("White"),false,false,true)
		RH.C0=clerp(RH.C0,cf(1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
		LH.C0=clerp(LH.C0,cf(-1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(-90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
		RootJoint.C0=clerp(RootJoint.C0,RootCF*cf(0,0,0 + 0.05 * math.cos(1 / 28))*angles(math.rad(0 - 1 * math.cos(1 / 34)),math.rad(0),math.rad(0)),.1)
		tors.Neck.C0=clerp(tors.Neck.C0,necko*angles(math.rad(10 - 2.5 * math.cos(1 / 32)),math.rad(0 + 15 * math.cos(1 / 0.25)),math.rad(-20 - 5 * math.cos(1 / 0.465))),.1)
		RW.C0=clerp(RW.C0,cf(1.35,0.5 + 0.1 * math.cos(sine / 28),0.05)*angles(math.rad(0),math.rad(-10),math.rad(10)),.1)
		LW.C0=clerp(LW.C0,cf(-1.35,0.5 + 0.1 * math.cos(sine / 28),0.05)*angles(math.rad(90),math.rad(-10),math.rad(10)),.1)
	end
	CFuncs["Sound"].Create("rbxassetid://912078533",cnglow1,10,1)
	RootPart.CFrame = chinchilla.Hit *CFrame.new(0,2,0)
	for i=1,25 do
		swait()
		RH.C0=clerp(RH.C0,cf(1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
		LH.C0=clerp(LH.C0,cf(-1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(-90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
		RootJoint.C0=clerp(RootJoint.C0,RootCF*cf(0,0,0 + 0.05 * math.cos(1 / 28))*angles(math.rad(0 - 1 * math.cos(1 / 34)),math.rad(0),math.rad(0)),.1)
		tors.Neck.C0=clerp(tors.Neck.C0,necko*angles(math.rad(10 - 2.5 * math.cos(1 / 32)),math.rad(0 + 15 * math.cos(1 / 0.25)),math.rad(-20 - 5 * math.cos(1 / 0.465))),.1)
		RW.C0=clerp(RW.C0,cf(1.35,0.5 + 0.1 * math.cos(sine / 28),0.05)*angles(math.rad(0),math.rad(-10),math.rad(10)),.1)
		LW.C0=clerp(LW.C0,cf(-1.35,0.5 + 0.1 * math.cos(sine / 28),0.05)*angles(math.rad(180),math.rad(-10),math.rad(10)),.1)
	end
	CFuncs["Sound"].Create("rbxassetid://912067661",cnglow1,10,1)
	for i=1,100 do
		swait()
		RH.C0=clerp(RH.C0,cf(1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
		LH.C0=clerp(LH.C0,cf(-1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(-90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
		RootJoint.C0=clerp(RootJoint.C0,RootCF*cf(0,0,0 + 0.05 * math.cos(1 / 28))*angles(math.rad(0 - 1 * math.cos(1 / 34)),math.rad(0),math.rad(0)),.1)
		Torso.Neck.C0=clerp(Torso.Neck.C0,necko*angles(math.rad(10 - 2.5 * math.cos(1 / 32)),math.rad(0 - 15 * math.cos(1 / 0.25)),math.rad(20 - 5 * math.cos(1 / 0.465))),.1)
		RW.C0=clerp(RW.C0,cf(-0.8,0.75,0.3)*angles(math.rad(90),math.rad(0),math.rad(-40 - 10 * math.cos(1 / 25))),.1)
		LW.C0=clerp(LW.C0,cf(-1.2,-0.3 + 0.5 * math.cos(1 / 28),0.05)*angles(math.rad(90),math.rad(-10),math.rad(10)),.1)
	end
	attack=false;
	hum.WalkSpeed=16;
	hum.JumpPower=50;
end

function execute()
	local targetted = nil
	if chinchilla.Target.Parent ~= char and chinchilla.Target.Parent.Parent ~= char and chinchilla.Target.Parent:FindFirstChildOfClass("Humanoid") ~= nil then
		targetted = chinchilla.Target.Parent
	else
		CFuncs["Sound"].Create("rbxassetid://7649721525",hed,1,1);
		local chcne=math.random(1,4)
		if chcne==1 then
			chatfunc("Your aim is trash, "..plr.Name..".",colror(r/255,g/255,b/255))
		elseif chcne==2 then
			chatfunc("Are you even aiming at anyone, "..plr.Name.."?",colror(r/255,g/255,b/255))
		elseif chcne==3 then
			chatfunc("You can do better at aiming than THAT, "..plr.Name..".",colror(r/255,g/255,b/255))
		elseif chcne==4 then
			chatfunc("Either you missed, or you just randomly pressed a button, "..plr.Name..".",colror(r/255,g/255,b/255))
		end
	end
	if targetted ~= nil then
		attack = true
		hum.WalkSpeed = 0
		hum.JumpPower = 0
		targetted.Head.Anchored = true
		local originalpos = root.CFrame
		RootPart.CFrame = targetted.Head.CFrame * CFrame.new(0,-2,4)
		CFuncs["Sound"].Create("rbxassetid://235097614",root,1,3)
		for i=1,25 do
			swait()
			RH.C0=clerp(RH.C0,cf(1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
			LH.C0=clerp(LH.C0,cf(-1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(-90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
			RootJoint.C0=clerp(RootJoint.C0,RootCF*cf(0,0,0 + 0.05 * math.cos(1 / 28))*angles(math.rad(0 - 1 * math.cos(1 / 34)),math.rad(0),math.rad(0)),.1)
			tors.Neck.C0=clerp(tors.Neck.C0,necko*angles(math.rad(10 - 2.5 * math.cos(1 / 32)),math.rad(0 + 15 * math.cos(1 / 0.25)),math.rad(-20 - 5 * math.cos(1 / 0.465))),.1)
			RW.C0=clerp(RW.C0,cf(1.35,0.5 + 0.1 * math.cos(sine / 28),0.05)*angles(math.rad(0),math.rad(-10),math.rad(10)),.1)
			LW.C0=clerp(LW.C0,cf(-1.35,0.5 + 0.1 * math.cos(sine / 28),0.05)*angles(math.rad(90),math.rad(-10),math.rad(10)),.1)
		end
		CFuncs["Sound"].Create("rbxassetid://912078533",cnglow1,10,1)
		dmg(targetted)
		for i=1,25 do
			swait()
			RH.C0=clerp(RH.C0,cf(1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
			LH.C0=clerp(LH.C0,cf(-1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(-90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
			RootJoint.C0=clerp(RootJoint.C0,RootCF*cf(0,0,0 + 0.05 * math.cos(1 / 28))*angles(math.rad(0 - 1 * math.cos(1 / 34)),math.rad(0),math.rad(0)),.1)
			tors.Neck.C0=clerp(tors.Neck.C0,necko*angles(math.rad(10 - 2.5 * math.cos(1 / 32)),math.rad(0 + 15 * math.cos(1 / 0.25)),math.rad(-20 - 5 * math.cos(1 / 0.465))),.1)
			RW.C0=clerp(RW.C0,cf(1.35,0.5 + 0.1 * math.cos(sine / 28),0.05)*angles(math.rad(0),math.rad(-10),math.rad(10)),.1)
			LW.C0=clerp(LW.C0,cf(-1.35,0.5 + 0.1 * math.cos(sine / 28),0.05)*angles(math.rad(180),math.rad(-10),math.rad(10)),.1)
		end
		CFuncs["Sound"].Create("rbxassetid://235097614",root,1,3)
		root.CFrame = originalpos
		CFuncs["Sound"].Create("rbxassetid://912067661",cnglow1,10,1)
		for i=1,100 do
			swait()
			RH.C0=clerp(RH.C0,cf(1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
			LH.C0=clerp(LH.C0,cf(-1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(-90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
			RootJoint.C0=clerp(RootJoint.C0,RootCF*cf(0,0,0 + 0.05 * math.cos(1 / 28))*angles(math.rad(0 - 1 * math.cos(1 / 34)),math.rad(0),math.rad(0)),.1)
			Torso.Neck.C0=clerp(Torso.Neck.C0,necko*angles(math.rad(10 - 2.5 * math.cos(1 / 32)),math.rad(0 - 15 * math.cos(1 / 0.25)),math.rad(20 - 5 * math.cos(1 / 0.465))),.1)
			RW.C0=clerp(RW.C0,cf(-0.8,0.75,0.3)*angles(math.rad(90),math.rad(0),math.rad(-40 - 10 * math.cos(1 / 25))),.1)
			LW.C0=clerp(LW.C0,cf(-1.2,-0.3 + 0.5 * math.cos(1 / 28),0.05)*angles(math.rad(90),math.rad(-10),math.rad(10)),.1)
		end
		attack=false;
		hum.WalkSpeed=16;
		hum.JumpPower=50;
	end
end

function shoot()
	attack = true
	hum.WalkSpeed = 0
	hum.JumpPower = 0
	CFuncs["Sound"].Create("rbxassetid://136007472", root, 2.5, 1.25)
	CFuncs["Sound"].Create("rbxassetid://74718359851540", root, 4, 1)
	for i=1,45 do
		swait()
		root.CFrame=FaceMouse()[1]
		sphereMKCharge(5,-0.25,"Add",orbbulletposthingyidk.CFrame*CFrame.Angles(math.rad(math.random(-360,360)),math.rad(math.random(-360,360)),math.rad(math.random(-360,360))),0.5,0.5,5,-0.005,BrickColor.new("White"),10)
		sphere(0,"Add",orbbulletposthingyidk.CFrame,Vector3.new(.5,.5,.5),1,BrickColor.new("White"),false,false,true)
		RH.C0=clerp(RH.C0,cf(1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
		LH.C0=clerp(LH.C0,cf(-1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(-90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
		RootJoint.C0=clerp(RootJoint.C0,RootCF*cf(0,0,0 + 0.05 * math.cos(1 / 28))*angles(math.rad(0 - 1 * math.cos(1 / 34)),math.rad(0),math.rad(0)),.1)
		tors.Neck.C0=clerp(tors.Neck.C0,necko*angles(math.rad(10 - 2.5 * math.cos(1 / 32)),math.rad(0 + 15 * math.cos(1 / 0.25)),math.rad(-20 - 5 * math.cos(1 / 0.465))),.1)
		RW.C0=clerp(RW.C0,cf(1.35,0.5 + 0.1 * math.cos(sine / 28),0.05)*angles(math.rad(0),math.rad(-10),math.rad(10)),.1)
		LW.C0=clerp(LW.C0,cf(-1.35,0.5 + 0.1 * math.cos(sine / 28),0.05)*angles(math.rad(90),math.rad(-10),math.rad(10)),.1)
	end
	CFuncs["Sound"].Create("rbxassetid://912078533",cnglow1,10,1)
	for i=1,25 do
		swait()
		RH.C0=clerp(RH.C0,cf(1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
		LH.C0=clerp(LH.C0,cf(-1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(-90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
		RootJoint.C0=clerp(RootJoint.C0,RootCF*cf(0,0,0 + 0.05 * math.cos(1 / 28))*angles(math.rad(0 - 1 * math.cos(1 / 34)),math.rad(0),math.rad(0)),.1)
		tors.Neck.C0=clerp(tors.Neck.C0,necko*angles(math.rad(10 - 2.5 * math.cos(1 / 32)),math.rad(0 + 15 * math.cos(1 / 0.25)),math.rad(-20 - 5 * math.cos(1 / 0.465))),.1)
		RW.C0=clerp(RW.C0,cf(1.35,0.5 + 0.1 * math.cos(sine / 28),0.05)*angles(math.rad(0),math.rad(-10),math.rad(10)),.1)
		LW.C0=clerp(LW.C0,cf(-1.35,0.5 + 0.1 * math.cos(sine / 28),0.05)*angles(math.rad(180),math.rad(-10),math.rad(10)),.1)
	end
	for i = 0, 14 do
		PixelBlock(3,math.random(4,8),"Add",mouse.Hit*CFrame.Angles(math.rad(math.random(-360,360)),math.rad(math.random(-360,360)),math.rad(math.random(-360,360))),3,3,3,0.03,BrickColor.new("White"),0)
	end
	sphere(10,"Add",mouse.Hit,vt(0,0,0),1,BrickColor.new("White"))
	for i = 0, 14 do
		PixelBlock(3,math.random(4,8),"Add",mouse.Hit*CFrame.Angles(math.rad(math.random(-360,360)),math.rad(math.random(-360,360)),math.rad(math.random(-360,360))),3,3,3,0.03,BrickColor.new("White"),0)
	end
	sphere(10,"Add",mouse.Hit,vt(0,0,0),1,BrickColor.new("White"))
	for i, v in pairs(FindNearestHead(mouse.Hit.Position, 20)) do
		if v:FindFirstChild('Head') then
			dmg(v)
		end
	end
	CFuncs["Sound"].Create("rbxassetid://912067661",cnglow1,10,1)
	for i=1,100 do
		swait()
		RH.C0=clerp(RH.C0,cf(1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
		LH.C0=clerp(LH.C0,cf(-1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(-90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
		RootJoint.C0=clerp(RootJoint.C0,RootCF*cf(0,0,0 + 0.05 * math.cos(1 / 28))*angles(math.rad(0 - 1 * math.cos(1 / 34)),math.rad(0),math.rad(0)),.1)
		Torso.Neck.C0=clerp(Torso.Neck.C0,necko*angles(math.rad(10 - 2.5 * math.cos(1 / 32)),math.rad(0 - 15 * math.cos(1 / 0.25)),math.rad(20 - 5 * math.cos(1 / 0.465))),.1)
		RW.C0=clerp(RW.C0,cf(-0.8,0.75,0.3)*angles(math.rad(90),math.rad(0),math.rad(-40 - 10 * math.cos(1 / 25))),.1)
		LW.C0=clerp(LW.C0,cf(-1.2,-0.3 + 0.5 * math.cos(1 / 28),0.05)*angles(math.rad(90),math.rad(-10),math.rad(10)),.1)
	end
	attack=false;
	hum.WalkSpeed=16;
	hum.JumpPower=50;
end

function killall()
	if killallcooldown==true then
		chatfunc("You need to wait to use this, "..plr.Name..".",colror(r/255,g/255,b/255))
	else
	killallcooldown=true;
	attack=true;
	hum.WalkSpeed=0;
	hum.JumpPower=0;
	for _,v in game.Workspace:GetDescendants() do
		if v:IsA("Model") and v.Name~=char.Name then
			if v:FindFirstChildOfClass("Humanoid") then
				local originalpos = root.CFrame
				RootPart.CFrame = v.Head.CFrame * CFrame.new(0,-2,4)
				CFuncs["Sound"].Create("rbxassetid://235097614",root,1,3)
				for i=1,5 do
					swait()
					RH.C0=clerp(RH.C0,cf(1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
					LH.C0=clerp(LH.C0,cf(-1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(-90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
					RootJoint.C0=clerp(RootJoint.C0,RootCF*cf(0,0,0 + 0.05 * math.cos(1 / 28))*angles(math.rad(0 - 1 * math.cos(1 / 34)),math.rad(0),math.rad(0)),.1)
					tors.Neck.C0=clerp(tors.Neck.C0,necko*angles(math.rad(10 - 2.5 * math.cos(1 / 32)),math.rad(0 + 15 * math.cos(1 / 0.25)),math.rad(-20 - 5 * math.cos(1 / 0.465))),.1)
					RW.C0=clerp(RW.C0,cf(1.35,0.5 + 0.1 * math.cos(sine / 28),0.05)*angles(math.rad(0),math.rad(-10),math.rad(10)),.1)
					LW.C0=clerp(LW.C0,cf(-1.35,0.5 + 0.1 * math.cos(sine / 28),0.05)*angles(math.rad(90),math.rad(-10),math.rad(10)),.1)
				end
				CFuncs["Sound"].Create("rbxassetid://912078533",cnglow1,10,1)
				dmg(v)
				for i=1,5 do
					swait()
					RH.C0=clerp(RH.C0,cf(1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
					LH.C0=clerp(LH.C0,cf(-1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(-90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
					RootJoint.C0=clerp(RootJoint.C0,RootCF*cf(0,0,0 + 0.05 * math.cos(1 / 28))*angles(math.rad(0 - 1 * math.cos(1 / 34)),math.rad(0),math.rad(0)),.1)
					tors.Neck.C0=clerp(tors.Neck.C0,necko*angles(math.rad(10 - 2.5 * math.cos(1 / 32)),math.rad(0 + 15 * math.cos(1 / 0.25)),math.rad(-20 - 5 * math.cos(1 / 0.465))),.1)
					RW.C0=clerp(RW.C0,cf(1.35,0.5 + 0.1 * math.cos(sine / 28),0.05)*angles(math.rad(0),math.rad(-10),math.rad(10)),.1)
					LW.C0=clerp(LW.C0,cf(-1.35,0.5 + 0.1 * math.cos(sine / 28),0.05)*angles(math.rad(180),math.rad(-10),math.rad(10)),.1)
				end
				CFuncs["Sound"].Create("rbxassetid://235097614",root,1,3)
				root.CFrame = originalpos
			end
		end
	end
	CFuncs["Sound"].Create("rbxassetid://912067661",cnglow1,10,1)
	for i=1,100 do
		swait()
		RH.C0=clerp(RH.C0,cf(1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
		LH.C0=clerp(LH.C0,cf(-1,-1 - 0.05 * math.cos(1 / 28),0)*angles(math.rad(0),math.rad(-90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(1 / 34))),.1)
		RootJoint.C0=clerp(RootJoint.C0,RootCF*cf(0,0,0 + 0.05 * math.cos(1 / 28))*angles(math.rad(0 - 1 * math.cos(1 / 34)),math.rad(0),math.rad(0)),.1)
		Torso.Neck.C0=clerp(Torso.Neck.C0,necko*angles(math.rad(10 - 2.5 * math.cos(1 / 32)),math.rad(0 - 15 * math.cos(1 / 0.25)),math.rad(20 - 5 * math.cos(1 / 0.465))),.1)
		RW.C0=clerp(RW.C0,cf(-0.8,0.75,0.3)*angles(math.rad(90),math.rad(0),math.rad(-40 - 10 * math.cos(1 / 25))),.1)
		LW.C0=clerp(LW.C0,cf(-1.2,-0.3 + 0.5 * math.cos(1 / 28),0.05)*angles(math.rad(90),math.rad(-10),math.rad(10)),.1)
	end
	attack=false;
	hum.WalkSpeed=16;
	hum.JumpPower=50;
	wait(60)
	killallcooldown=false;
	end
end

--// Controls Gui \\--

local nyoooooooooooooooo=Instance.new("ScreenGui",PlrGui)
nyoooooooooooooooo.Name="ENERGY RUSH V2 CONTROLS"
local thisisthenameofthescripthowcoolwow=Instance.new("Frame",nyoooooooooooooooo)
thisisthenameofthescripthowcoolwow.Position=UDim2.new(0.8, 0, 0.70, 0)
thisisthenameofthescripthowcoolwow.Size=UDim2.new(0.26, 0, 0.07, 0)
thisisthenameofthescripthowcoolwow.BackgroundColor3=Color3.new(0,0,0)
thisisthenameofthescripthowcoolwow.Transparency=1
thisisthenameofthescripthowcoolwow.BorderSizePixel=0
local jkthisisthenameofthescript=Instance.new("TextLabel",thisisthenameofthescripthowcoolwow)
jkthisisthenameofthescript.Text="Energy Rush V2"
jkthisisthenameofthescript.TextStrokeColor3=colror(0,0,0)
jkthisisthenameofthescript.TextStrokeTransparency=0
jkthisisthenameofthescript.BackgroundTransparency=1
jkthisisthenameofthescript.TextSize="14"
local whomadethisscriptframe=Instance.new("Frame",nyoooooooooooooooo)
whomadethisscriptframe.Position=UDim2.new(0.8, 0, 0.74, 0)
whomadethisscriptframe.Size=UDim2.new(0.26, 0, 0.07, 0)
whomadethisscriptframe.BackgroundColor3=Color3.new(0,0,0)
whomadethisscriptframe.Transparency=1
whomadethisscriptframe.BorderSizePixel=0
local whomadethisscripttext=Instance.new("TextLabel",whomadethisscriptframe)
whomadethisscripttext.Text="By: Stratus_bl"
whomadethisscripttext.TextStrokeColor3=colror(0,0,0)
whomadethisscripttext.TextStrokeTransparency=0
whomadethisscripttext.BackgroundTransparency=1
whomadethisscripttext.TextSize="14"
local odna=Instance.new("Frame",nyoooooooooooooooo)
odna.Position=UDim2.new(0.8, 0, 0.82, 0)
odna.Size=UDim2.new(0.26, 0, 0.07, 0)
odna.BackgroundColor3=Color3.new(0,0,0)
odna.Transparency=1
odna.BorderSizePixel=0
local attackonekey=Instance.new("TextLabel",odna)
attackonekey.Text="[X] - Execute"
attackonekey.TextStrokeColor3=colror(0,0,0)
attackonekey.TextStrokeTransparency=0
attackonekey.BackgroundTransparency=1
attackonekey.TextSize="14"
local dva=Instance.new("Frame",nyoooooooooooooooo)
dva.Position=UDim2.new(0.8, 0, 0.78, 0)
dva.Size=UDim2.new(0.26, 0, 0.07, 0)
dva.BackgroundColor3=Color3.new(0,0,0)
dva.Transparency=1
dva.BorderSizePixel=0
local attacktwkey=Instance.new("TextLabel",dva)
attacktwkey.Text="[N] - Teleport"
attacktwkey.TextStrokeColor3=colror(0,0,0)
attacktwkey.TextStrokeTransparency=0
attacktwkey.BackgroundTransparency=1
attacktwkey.TextSize="14"
local tre=Instance.new("Frame",nyoooooooooooooooo)
tre.Position=UDim2.new(0.8, 0, 0.94, 0)
tre.Size=UDim2.new(0.26, 0, 0.07, 0)
tre.BackgroundColor3=Color3.new(0,0,0)
tre.Transparency=1
tre.BorderSizePixel=0
local attacktrkey=Instance.new("TextLabel",tre)
attacktrkey.Text="[LMB] - Punch"
attacktrkey.TextStrokeColor3=colror(0,0,0)
attacktrkey.TextStrokeTransparency=0
attacktrkey.BackgroundTransparency=1
attacktrkey.TextSize="14"
local howdoihideframe=Instance.new("Frame",nyoooooooooooooooo)
howdoihideframe.Position=UDim2.new(0.8, 0, 0.98, 0)
howdoihideframe.Size=UDim2.new(0.26, 0, 0.07, 0)
howdoihideframe.BackgroundColor3=Color3.new(0,0,0)
howdoihideframe.Transparency=1
howdoihideframe.BorderSizePixel=0
local howdoihidetext=Instance.new("TextLabel",howdoihideframe)
howdoihidetext.Text="[L] - Hide Controls"
howdoihidetext.TextStrokeColor3=colror(0,0,0)
howdoihidetext.TextStrokeTransparency=0
howdoihidetext.BackgroundTransparency=1
howdoihidetext.TextSize="14"
local chutoru=Instance.new("Frame",nyoooooooooooooooo)
chutoru.Position=UDim2.new(0.8, 0, 0.86, 0)
chutoru.Size=UDim2.new(0.26, 0, 0.07, 0)
chutoru.BackgroundColor3=Color3.new(0,0,0)
chutoru.Transparency=1
chutoru.BorderSizePixel=0
local attackfrkey=Instance.new("TextLabel",chutoru)
attackfrkey.Text="[Z] - Shoot"
attackfrkey.TextStrokeColor3=colror(0,0,0)
attackfrkey.TextStrokeTransparency=0
attackfrkey.BackgroundTransparency=1
attackfrkey.TextSize="14"
local byet=Instance.new("Frame",nyoooooooooooooooo)
byet.Position=UDim2.new(0.8, 0, 0.90, 0)
byet.Size=UDim2.new(0.26, 0, 0.07, 0)
byet.BackgroundColor3=Color3.new(0,0,0)
byet.Transparency=1
byet.BorderSizePixel=0
local attackfvkey=Instance.new("TextLabel",byet)
attackfvkey.Text="[V] - Kill All (60 Second Cooldown)"
attackfvkey.TextStrokeColor3=colror(0,0,0)
attackfvkey.TextStrokeTransparency=0
attackfvkey.BackgroundTransparency=1
attackfvkey.TextSize="14"

--// Assign things to keys \\--

chinchilla.Button1Down:Connect(function()
	if not attack then
		lilpunch()
	end
end)


chinchilla.KeyDown:Connect(function(k)
	if attack ==false then
		if k=="x" then
			execute()
		elseif k=="n" then
			teleport()
		elseif k=="z" then
			shoot()
		elseif k=="v" then
			killall()
		end
	end
	if k=="l" then
		nyoooooooooooooooo.Enabled=not nyoooooooooooooooo.Enabled
	end
end)

--// Wrap the whole script up \\--

hum.Name="ENERGYRUSH"
local forcefield=Instance.new("ForceField",char);
forcefield.Visible=false;
hum.MaxHealth=math.huge;
hum.Health=hum.MaxHealth;

coroutine.resume(coroutine.create(function()
	while true do
		swait()
		CameraManager()
		sine=sine+change
		if introed==true then
		text.TextColor3=colror(r/255, g/255, b/255)
		text.TextStrokeColor3=colror(r/500, g/500, b/500)
		ringycolor.Color=colror(r/255,g/255,b/255)
		ringycolorjunior.Color=colror(r/255,g/255,b/255)
		cnglow1.Color=colror(r/255,g/255,b/255)
		cnglow2.Color=colror(r/255,g/255,b/255)
		cnglow3.Color=colror(r/255,g/255,b/255)
		larm.Color=colror(r/255,g/255,b/255)
		core.Color=colror(r/255,g/255,b/255)
		attackonekey.TextColor3=colror(r/255,g/255,b/255)
		attackonekey.TextStrokeColor3=colror(r/500,g/500,b/500)
		attacktwkey.TextColor3=colror(r/255,g/255,b/255)
		attacktwkey.TextStrokeColor3=colror(r/500,g/500,b/500)
		jkthisisthenameofthescript.TextColor3=colror(r/255,g/255,b/255)
		jkthisisthenameofthescript.TextStrokeColor3=colror(r/500,g/500,b/500)
		attacktrkey.TextColor3=colror(r/255,g/255,b/255)
		attacktrkey.TextStrokeColor3=colror(r/500,g/500,b/500)
		howdoihidetext.TextColor3=colror(r/255,g/255,b/255)
		howdoihidetext.TextStrokeColor3=colror(r/500,g/500,b/500)
		whomadethisscripttext.TextColor3=colror(r/255,g/255,b/255)
		whomadethisscripttext.TextStrokeColor3=colror(r/500,g/500,b/500)
		attackfrkey.TextColor3=colror(r/255,g/255,b/255)
		attackfrkey.TextStrokeColor3=colror(r/500,g/500,b/500)
		attackfvkey.TextColor3=colror(r/255,g/255,b/255)
		attackfvkey.TextStrokeColor3=colror(r/500,g/500,b/500)
		end
		if attack==false then
			local torvel=(RootPart.Velocity*Vector3.new(1,0,1)).magnitude 
			local velderp=RootPart.Velocity.y
			local hitfloor,posfloor=rayCast(RootPart.Position,(CFrame.new(RootPart.Position,RootPart.Position - Vector3.new(0,1,0))).lookVector,4,char)
			if torvel<1 and hitfloor~=nil then
				Anim="Idle"
				RH.C0=clerp(RH.C0,cf(1,-1 - 0.05 * math.cos(sine / 28),0)*angles(math.rad(0),math.rad(90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(sine / 34))),.1)
				LH.C0=clerp(LH.C0,cf(-1,-1 - 0.05 * math.cos(sine / 28),0)*angles(math.rad(0),math.rad(-90),math.rad(0))*angles(math.rad(-2.5),math.rad(0),math.rad(0 + 1 * math.cos(sine / 34))),.1)
				RootJoint.C0=clerp(RootJoint.C0,RootCF*cf(0,0,0 + 0.05 * math.cos(sine / 28))*angles(math.rad(0 - 1 * math.cos(sine / 34)),math.rad(0),math.rad(0)),.1)
				Torso.Neck.C0=clerp(Torso.Neck.C0,necko*angles(math.rad(5 - 2.5 * math.cos(sine / 28)),math.rad(0),math.rad(math.random(-10,10))),.1)
				RW.C0=clerp(RW.C0,cf(1.35,0.5 + 0.1 * math.cos(sine / 28),0.05)*angles(math.rad(0),math.rad(-10),math.rad(10)),.1)
				LW.C0=clerp(LW.C0,cf(-1.35,0.5 + 0.1 * math.cos(sine / 28),0.05)*angles(math.rad(0),math.rad(10),math.rad(math.random(-10,-5))),.1)
			elseif torvel>2 and torvel<173 and hitfloor~=nil then
				Anim="Walk"
				RH.C0=clerp(RH.C0,cf(1,-0.85,-0.15 - 0.15 * math.cos(sine / 4))*angles(math.rad(0),math.rad(90),math.rad(0))*angles(math.rad(0),math.rad(0 + 5 * math.cos(sine / 8)),math.rad(0 + 25 * math.cos(sine / 8))),.1)
				LH.C0=clerp(LH.C0,cf(-1,-0.85,-0.15 + 0.15 * math.cos(sine / 4))*angles(math.rad(0),math.rad(-90),math.rad(0))*angles(math.rad(0),math.rad(0 + 5 * math.cos(sine / 8)),math.rad(0 + 25 * math.cos(sine / 8))),.1)
				RootJoint.C0=clerp(RootJoint.C0,RootCF*cf(0,0,-0.15 - 0.1 * math.cos(sine / 4))*angles(math.rad(5),math.rad(0),math.rad(0 - 5 * math.cos(sine / 8))),.1)
				Torso.Neck.C0=clerp(Torso.Neck.C0,necko*angles(math.rad(10 + 2.5 * math.cos(sine / 100)),math.rad(0),math.rad(0 + 5 * math.cos(sine / 8))),.1)
				RW.C0=clerp(RW.C0,cf(1.5,0.5,0)*angles(math.rad(0 - 45 * math.cos(sine / 8)),math.rad(-0),math.rad(0 - 0 * math.cos(sine / 4))),.1)
				LW.C0=clerp(LW.C0,cf(-1.5,0.5,0)*angles(math.rad(0 + 45 * math.cos(sine / 8)),math.rad(-0),math.rad(0 - 0 * math.cos(sine / 4))),.1)
			elseif RootPart.Velocity.y > 1 and hitfloor==nil then 
				Anim="Jump"
				if attack==false then
					RH.C0=clerp(RH.C0,cf(1,-0.35 - 0.05 * math.cos(sine / 25),-0.75)*angles(math.rad(0),math.rad(90),math.rad(0))*angles(math.rad(-5),math.rad(0),math.rad(-20)),.1)
					LH.C0=clerp(LH.C0,cf(-1,-1 - 0.05 * math.cos(sine / 25),0)*angles(math.rad(0),math.rad(-90),math.rad(0))*angles(math.rad(-5),math.rad(0),math.rad(20)),.1)
					RootJoint.C0=clerp(RootJoint.C0,RootCF*cf(0,0,0 + 0.05 * math.cos(sine / 25))*angles(math.rad(-tors.Velocity.Y/6),math.rad(0),math.rad(0)),.1)
					Torso.Neck.C0=clerp(Torso.Neck.C0,necko*angles(math.rad(-2.5),math.rad(0),math.rad(0)),.1)
					RW.C0=clerp(RW.C0,cf(1.45,0.5 + 0.1 * math.cos(sine / 25),0)*angles(math.rad(-5),math.rad(0),math.rad(25)),.1)
					LW.C0=clerp(LW.C0,cf(-1.45,0.5 + 0.1 * math.cos(sine / 25),0)*angles(math.rad(-5),math.rad(0),math.rad(-25)),.1)
			elseif RootPart.Velocity.y < -1 and hitfloor==nil then 
				Anim="Fall"
				if attack==false then
					RH.C0=clerp(RH.C0,cf(1,-0.35 - 0.05 * math.cos(sine / 25),-0.75)*angles(math.rad(0),math.rad(90),math.rad(0))*angles(math.rad(-5),math.rad(0),math.rad(-20)),.1)
					LH.C0=clerp(LH.C0,cf(-1,-1 - 0.05 * math.cos(sine / 25),0)*angles(math.rad(0),math.rad(-90),math.rad(0))*angles(math.rad(-5),math.rad(0),math.rad(20)),.1)
					RootJoint.C0=clerp(RootJoint.C0,RootCF*cf(0,0,0 + 0.05 * math.cos(sine / 25))*angles(math.rad(-tors.Velocity.Y/6),math.rad(0),math.rad(0)),.1)
					Torso.Neck.C0=clerp(Torso.Neck.C0,necko*angles(math.rad(2.5),math.rad(0),math.rad(0)),.1)
					RW.C0=clerp(RW.C0,cf(1.45,0.5 + 0.1 * math.cos(sine / 25),0)*angles(math.rad(-15),math.rad(0),math.rad(55)),.1)
					LW.C0=clerp(LW.C0,cf(-1.45,0.5 + 0.1 * math.cos(sine / 25),0)*angles(math.rad(-15),math.rad(0),math.rad(-55)),.1)
				end
			end
			end
		end
	end
end))
print("Loaded.")
